app/models.py
from datetime import datetime
from flask import current_app
from app import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin, current_user


@login_manager.user_loader
def loader_user(user_id):
    return User.query.get(int(user_id))

class User(db.Model, UserMixin):
    __tablename__="users"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255), unique=True, nullable=False, index=True)
    email = db.Column(db.String(255), unique=True, nullable=False, index=True)
    encryptedpassword = db.Column(db.String(255),index=True)
    posts = db.relationship('Post', backref='user', lazy='dynamic')
    comments = db.relationship('Comment', backref='user', lazy='dynamic') 

    @property
    def password(self):
        raise AttributeError('Encrypted')

    @password.setter
    def password(self,password):
        self.encryptedpassword = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.encryptedpassword,password) 
    
    def save(self):
        db.session.add(self)
        db.session.commit()
       

    def __repr__(self):
        return f"User('{self.username}', '{self.email}'"



class Post(db.Model):
    __tablename__="posts"

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    content = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    comments = db.relationship('Comment', backref='post', lazy='dynamic')

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()


    @classmethod
    def get_post(cls,id):
        post = Post.query.filter_by(id=id).first()

        return post

    @classmethod
    def count_posts(cls,uname):
        user = User.query.filter_by(username=uname).first()
        posts = Post.query.filter_by(user_id=user.id).all()

        posts_count = 0
        for post in posts:
            posts_count += 1

        return posts_count


    def __repr__(self):
        return f"Post('{self.title}'"


class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer,primary_key = True)
    comment = db.Column(db.String(1000))
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    post_id = db.Column(db.Integer,db.ForeignKey("posts.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,post):
        comments = Comment.query.filter_by(post_id=post.id).all()
        return comments

    def __repr__(self):
        return f"Comment('{self.comment}'"

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import  StringField,SelectField,TextAreaField,SubmitField
from wtforms.validators import Required,DataRequired

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

class CommentForm(FlaskForm):
    comment = TextAreaField('Comment')
    submit = SubmitField('Submit') 

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail

mail = Mail()

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):
    app = Flask(__name__,instance_relative_config=True)
    app.config.from_object(config_options[config_name])

    mail.init_app(app)
    bootstrap.init_app(app)
    db.init_app(app)
    
    login_manager.init_app(app)
    
    # Register main blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # Register auth blueprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from .views import *

app/main/views.py
from flask_wtf import FlaskForm
from wtforms import  StringField,SelectField,TextAreaField,SubmitField
from wtforms.validators import Required
from flask_login import login_required, current_user
from flask import render_template, request, Blueprint, redirect, url_for, abort, flash
from app.models import User, Post, Comment
from . import main
from app import db
import urllib.request
from .forms import PostForm, CommentForm
from app.requests import getQuotes

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    #page = request.args.get('page',1,type=int)
    #posts = Post.query.order_by(Post.date_posted.desc()).paginate(per_page=5)
    quotes = getQuotes()
    posts = Post.query.all()

    title = "Home"
    return render_template('home.html', posts=posts, title=title, quotes=quotes)


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    posts_count = Post.count_posts(uname)

    if user is None:
        abort(404)

    title = "User"

    return render_template("profile.html", user = user,title=title, posts=posts, posts_count=posts_count)


@main.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post(): 
    form = PostForm()

    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data,user=current_user)

        #new_post = Post(title=title,post=post,user = current_user)

        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')

        return redirect(url_for('main.home')) 

    return render_template('create_post.html',form=form)


@main.route('/user/<uname>/posts')
def user_posts(uname):
    user = User.query.filter_by(username=uname).first()
    posts = Post.query.filter_by(user_id = user.id).all()
    posts_count = Post.count_posts(uname)

    return render_template("posts.html", user=user,posts=posts,posts_count=posts_count)


@main.route('/posts/all_posts')
def all_posts():

    #posts = Post.get_post()
    posts = Post.query.all()

    return render_template("all_posts.html", posts = posts)


@main.route('/post/<int:id>', methods = ['POST','GET'])
@login_required
def posts(id):
    post = Post.get_post(id)

    form = CommentForm()
    if form.validate_on_submit():
        comment = form.comment.data

        new_comment = Comment(comment = comment,user = current_user,post_id = post.id)

        new_comment.save_comment()


    comments = Comment.get_comments(post)

    return render_template("post.html", post = post, form = form, comments = comments)

app/templates/all_posts.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block content%}
<div class="jumbotron text-center">
    <h1>Posts</h1>
</div>
<div class="container">
    <hr>
    <div class="container">
        {{macro.displayPosts(posts)}}
    </div>
</div>
{%endblock%}

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

{%block styles %}
  {{super()}}
{% endblock %}

app/templates/comment.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
    <div class="container">
        <div class="row">

            {% if all_comments %}
                <div class="col-md" >
                    <h3 class="text-center" id="coms">Comments</h3>

                    {% for comment in all_comments %}
                       <div class="card w-90 mb-3" >
                           <div class="card-body">
                            <h5>{{comment.post.title}}</h5>
                             <p class="card-title">{{ comment.comment }}</p>
                             <p class="card-text">- {{comment.user.username}}</p>
                           </div>
                       </div>
                    {% endfor %}

                   </div>

                   <div class="col-md" >
                        {{wtf.quick_form(comment_form)}}
                   </div>
               </div>
            {%else%}

            <div class="card w-90 mb-3">
                <div class="card-body">
                  <p class="card-title">No comments available.</p>
                </div>
            </div> 
            <div class="col-md">
                    {{wtf.quick_form(form)}}
            </div>
            {%endif%}
    </div>
   
{% endblock%}

app/templates/create_post.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container">
        <div class="col-md-12">
            <h3>Create new post</h3>
            <hr>
            {{ wtf.quick_form(form) }}
        </div>

    </div>

{% endblock %}

app/templates/home.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block styles%}
    {{ super() }}

{%endblock%}

{%block content%}
<div class="jumbotron text-center">
    <h1><b>My Blog</b></h1>
</div>
<br>
<h4>{{macro.display_quotes(quotes)}}</h4>
<br>
<div class="container text-center" style="padding-bottom: 20px;">
    <a href="{{url_for('main.new_post')}}" class="btn btn-lg btn-success"><b>New Post</b></a>
    <hr>
    <br>
    <a href="{{url_for('main.all_posts')}}" class="btn btn-md btn-success -center">View Posts</a>
</div>
<br>
<hr>
{%endblock%}

app/templates/index.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block styles%}
    {{ super() }}

{%endblock%}

{%block content%}
<div class="jumbotron text-center">
    <h1><b>My Blog</b></h1>
</div>
<br>
<h4>{{macro.display_quotes(quotes)}}</h4>
<br>
<div class="container" style="padding-bottom: 20px;">
    <a href="{{url_for('main.new_post')}}" class="btn btn-primary">New Post</a>
</div>

<div class="container">
    <div class="container">
        <div class="container">
            <div class="container">
                <h3>Posts</h3>
                <a href="{{url_for('main.all_posts')}}" class="btn btn-success -center">View</a>
            </div>
        </div>
    </div>
</div>
{%endblock%}

app/templates/macros.html
{% macro displayPosts(posts_list)%}
    {%for post in posts_list%}
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 review-card">
            <div class="well well-lg">
                <h4>{{post.title}}</h4>
                <p>{{post.content| truncate(100)}}</p>
                <p>Written by:  {{post.user.username}} <a href="/post/{{post.id}}" class="btn btn-primary pull-right">View this post</a> </p>
            </div>
        </div>
    {%endfor%}
{%endmacro%}

{%macro displayComments(comments_list)%}
    {%for comment in comments_list%}
        <div class="col-md-12">
            <h5><i>'{{comment.comment}}' </i>&nbsp;&nbsp;by&nbsp;&nbsp;<b>{{comment.user.username}}</b></h5>
        </div>
    {%endfor%}
{%endmacro%}

{% macro display_quotes(quotes)%}
<div class="jumbotron container">
    <h3 class="text-center"><b>Random Quote</b></h3>
    <br>
    <h5 class="mt-3 text-success">'{{quotes.quote}}'</h5>
    <br>
    <b><i>~ {{quotes.author}}</i></b>
</div>
{%endmacro%}

app/templates/navbar.html
<div class="navbar navbar-inverse apperance" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        
            <a class="navbar-brand" href="/"> My Blog </a></button>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">  
                <li><a href="/"><b>Home</b></a></li>

                <ul class="nav navbar-nav navbar-right">
                  {% if current_user.is_authenticated %}
                  <li><a href="{{url_for('main.profile',uname=current_user.username)}}" style="color:white;padding:15px;"><b>{{current_user.username}}</b></a></li>
                  <li><a href="{{url_for('main.new_post')}}">Create Post</a></li>
                  <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                  {% else %}
                  <li><a href="{{url_for('auth.login')}}"><b>Sign in</b></a></li>
                  {%endif%}
                </ul>
            </ul>       
        </div>
    </div>
  </div>



<div class="navbar navbar-light" role="navigation" style="margin-bottom:0; border-bottom: 1px solid;">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand"> My Blog </a>
        </div>
        <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/">Home</a></li>
                    <li><a href="{{url_for('main.all_posts')}}">Posts</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{current_user.username| capitalize}} <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{url_for('main.profile',uname=current_user.username)}}">My Profile</a></li>
                            <li><a href="{{url_for('main.user_posts',uname=current_user.username)}}">My Posts</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                </ul>
                {%endif%}
            </div>
    </div>
</div>

app/templates/new_pitch.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
 {%block styles%}
  {{ super() }}

{%endblock%}

{% block content %}
<div class="container" style="text-align:center">
  <h3>{{category.name|upper}} Post</h3>
  <div class="well">
    <hr>
    {{wtf.quick_form(pitch_form)}}
 </div>
</div>
{% endblock %}

app/templates/new_post.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
 {%block styles%}
  {{ super() }}

{%endblock%}

{% block content %}
<div class="container" style="text-align:center">
  <div class="well">
    <hr>
    {{wtf.quick_form(form)}}
 </div>
</div>
{% endblock %}

app/templates/post.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% import "bootstrap/wtf.html" as wtf %}

{%block styles%}
    {{ super() }}
{%endblock%}

{%block content%}
<div class="container">
    <div class="row">
        <h3><b>{{post.title}}</b></h3>
        <hr>
        <p>{{post.content}}</p>
    </div>
    <br>
    <br>
    <br>
    <div class="row">
        {% if current_user.is_authenticated %}
            {{ wtf.quick_form(form) }}
        {%endif%}
        <hr>
        <br>
        <h4 style="text-align:center"><b>Comments</b></h4>
        <br>
        {{macro.displayComments(comments)}}
        <br>
    </div>

</div>
{%endblock%}

app/templates/posts.html
{% extends 'base.html'%}
{%import 'macros.html' as macro%}

{% block content %}
<div class="container">
    <div class="row">
        <h3> {{user.username| capitalize}} </h3>
        <hr>
        <div class="col-md-9">
            <p>No of posts: {{posts_count}}</p>
        </div>
        <div class="row">
            <div class="col-md-12">
              <h3> Posts </h3>
              <hr>
               {{macro.displayPosts(posts)}}
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="container">
        <h3> {{user.username| capitalize}} </h3>
        <hr>
        <div class="container">
            <p>Email: {{user.email}}</p>
            <br>
            <p>No of posts: {{posts_count}}</p>
        </div>
    </div>
</div>
{% endblock %}